name: Daily Stock Alerts

on:
  schedule:
    # Run at 8:05 PM UTC (4:05 PM ET)
    - cron: '5 20 * * *'
  
  # Allow manual trigger for testing
  workflow_dispatch:

jobs:
  send-stock-alerts:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run stock alerts script
      env:
        FMP_API_KEY: ${{ secrets.FMP_API_KEY }}
        EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
        PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
        SMTP_SERVER: smtp.gmail.com
        SMTP_PORT: 587
      run: |
        python main.py --test